name: Build & Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: pip install -e ".[dev]"
        
      - name: Build Executable
        run: pyinstaller --onefile --noconsole --uac-admin --name woptimizer --clean src/woptimizer/__main__.py
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/woptimizer.exe
